// AUTO-GENERATED by scripts/generate-model-rates.mjs.
// Do not edit by hand. Edit scripts/model-rates.json and run
// `pnpm generate:model-rates`.

package costrate

const CatalogHash = "007d5388491589d54de21d23f3914d77fdea161e39cc5b01875a27736e2a9c95"

type Rate struct {
	Input      float64
	Output     float64
	CacheRead  float64
	CacheWrite float64
}

var table = map[string]Rate{
	"claude-fable-5": {Input: 10, Output: 50, CacheRead: 1, CacheWrite: 12.5},
	"claude-fable-5-1": {Input: 10, Output: 50, CacheRead: 0.25, CacheWrite: 12.5},
	"claude-haiku-3-5": {Input: 0.8, Output: 4, CacheRead: 0.08, CacheWrite: 1},
	"claude-haiku-4-5": {Input: 1, Output: 5, CacheRead: 0.1, CacheWrite: 1.25},
	"claude-opus-4": {Input: 15, Output: 75, CacheRead: 1.5, CacheWrite: 18.75},
	"claude-opus-4-1": {Input: 15, Output: 75, CacheRead: 1.5, CacheWrite: 18.75},
	"claude-opus-4-5": {Input: 5, Output: 25, CacheRead: 0.5, CacheWrite: 6.25},
	"claude-opus-4-6": {Input: 5, Output: 25, CacheRead: 0.5, CacheWrite: 6.25},
	"claude-opus-4-7": {Input: 5, Output: 25, CacheRead: 0.5, CacheWrite: 6.25},
	"claude-opus-4-8": {Input: 5, Output: 25, CacheRead: 0.5, CacheWrite: 6.25},
	"claude-opus-5": {Input: 5, Output: 25, CacheRead: 0.5, CacheWrite: 6.25},
	"claude-sonnet-4": {Input: 3, Output: 15, CacheRead: 0.3, CacheWrite: 3.75},
	"claude-sonnet-4-5": {Input: 3, Output: 15, CacheRead: 0.3, CacheWrite: 3.75},
	"claude-sonnet-4-6": {Input: 3, Output: 15, CacheRead: 0.3, CacheWrite: 3.75},
	"claude-sonnet-5": {Input: 2, Output: 10, CacheRead: 0.2, CacheWrite: 2.5},
	"cursor": {Input: 3, Output: 15, CacheRead: 0.5, CacheWrite: 0},
	"cursor/auto": {Input: 1.25, Output: 6, CacheRead: 0.25, CacheWrite: 0},
	"cursor/composer-1": {Input: 1.25, Output: 10, CacheRead: 0.125, CacheWrite: 0},
	"cursor/composer-1.5": {Input: 3.5, Output: 17.5, CacheRead: 0.35, CacheWrite: 0},
	"cursor/composer-2": {Input: 0.5, Output: 2.5, CacheRead: 0.2, CacheWrite: 0},
	"cursor/composer-2-fast": {Input: 1.5, Output: 7.5, CacheRead: 0.35, CacheWrite: 0},
	"cursor/composer-2.5": {Input: 0.5, Output: 2.5, CacheRead: 0.2, CacheWrite: 0},
	"cursor/composer-2.5-fast": {Input: 3, Output: 15, CacheRead: 0.5, CacheWrite: 0},
	"deepseek-chat": {Input: 0.14, Output: 0.28, CacheRead: 0.0028, CacheWrite: 0.14},
	"deepseek-reasoner": {Input: 0.14, Output: 0.28, CacheRead: 0.0028, CacheWrite: 0.14},
	"deepseek-v4-flash": {Input: 0.14, Output: 0.28, CacheRead: 0.0028, CacheWrite: 0.14},
	"deepseek-v4-pro": {Input: 1.74, Output: 3.48, CacheRead: 0.0145, CacheWrite: 1.74},
	"glm-4.5": {Input: 0.6, Output: 2.2, CacheRead: 0.11, CacheWrite: 0.6},
	"glm-4.5-air": {Input: 0.2, Output: 1.1, CacheRead: 0.03, CacheWrite: 0.2},
	"glm-4.5-airx": {Input: 1.1, Output: 4.5, CacheRead: 0.22, CacheWrite: 1.1},
	"glm-4.5-flash": {Input: 0, Output: 0, CacheRead: 0, CacheWrite: 0},
	"glm-4.5-x": {Input: 2.2, Output: 8.9, CacheRead: 0.45, CacheWrite: 2.2},
	"glm-4.6": {Input: 0.6, Output: 2.2, CacheRead: 0.11, CacheWrite: 0.6},
	"glm-4.7": {Input: 0.6, Output: 2.2, CacheRead: 0.11, CacheWrite: 0.6},
	"glm-4.7-flash": {Input: 0, Output: 0, CacheRead: 0, CacheWrite: 0},
	"glm-4.7-flashx": {Input: 0.07, Output: 0.4, CacheRead: 0.01, CacheWrite: 0.07},
	"glm-5": {Input: 1, Output: 3.2, CacheRead: 0.2, CacheWrite: 1},
	"glm-5-turbo": {Input: 1.2, Output: 4, CacheRead: 0.24, CacheWrite: 1.2},
	"glm-5.1": {Input: 1.4, Output: 4.4, CacheRead: 0.26, CacheWrite: 1.4},
	"gpt-4o": {Input: 2.5, Output: 10, CacheRead: 1.25, CacheWrite: 2.5},
	"gpt-4o-mini": {Input: 0.15, Output: 0.6, CacheRead: 0.075, CacheWrite: 0.15},
	"gpt-5": {Input: 1.25, Output: 10, CacheRead: 0.125, CacheWrite: 1.25},
	"gpt-5-codex": {Input: 1.25, Output: 10, CacheRead: 0.125, CacheWrite: 1.25},
	"gpt-5-mini": {Input: 0.25, Output: 2, CacheRead: 0.025, CacheWrite: 0.25},
	"gpt-5-nano": {Input: 0.05, Output: 0.4, CacheRead: 0.005, CacheWrite: 0.05},
	"gpt-5.3-codex": {Input: 1.75, Output: 14, CacheRead: 0.175, CacheWrite: 1.75},
	"gpt-5.4": {Input: 2.5, Output: 15, CacheRead: 0.25, CacheWrite: 2.5},
	"gpt-5.4-mini": {Input: 0.75, Output: 4.5, CacheRead: 0.075, CacheWrite: 0.75},
	"gpt-5.5": {Input: 5, Output: 30, CacheRead: 0.5, CacheWrite: 5},
	"gpt-5.6-luna": {Input: 1, Output: 6, CacheRead: 0.1, CacheWrite: 1.25},
	"gpt-5.6-sol": {Input: 5, Output: 30, CacheRead: 0.5, CacheWrite: 6.25},
	"gpt-5.6-terra": {Input: 2.5, Output: 15, CacheRead: 0.25, CacheWrite: 3.125},
	"grok-4.20-0309-non-reasoning": {Input: 1.25, Output: 2.5, CacheRead: 0.2, CacheWrite: 1.25},
	"grok-4.20-0309-reasoning": {Input: 1.25, Output: 2.5, CacheRead: 0.2, CacheWrite: 1.25},
	"grok-4.20-multi-agent-0309": {Input: 1.25, Output: 2.5, CacheRead: 0.2, CacheWrite: 1.25},
	"grok-4.3": {Input: 1.25, Output: 2.5, CacheRead: 0.2, CacheWrite: 1.25},
	"grok-4.5": {Input: 2, Output: 6, CacheRead: 0.3, CacheWrite: 2},
	"grok-4.6": {Input: 2, Output: 6, CacheRead: 0.5, CacheWrite: 2},
	"grok-build-0.1": {Input: 1, Output: 2, CacheRead: 0.2, CacheWrite: 1},
	"kimi-k2.6": {Input: 0.95, Output: 4, CacheRead: 0.16, CacheWrite: 0.95},
	"kimi-k3": {Input: 3, Output: 15, CacheRead: 0.3, CacheWrite: 3},
	"kimi/k3": {Input: 3, Output: 15, CacheRead: 0.3, CacheWrite: 3},
	"o3": {Input: 2, Output: 8, CacheRead: 0.5, CacheWrite: 2},
	"o3-mini": {Input: 1.1, Output: 4.4, CacheRead: 0.55, CacheWrite: 1.1},
	"o4-mini": {Input: 1.1, Output: 4.4, CacheRead: 0.275, CacheWrite: 1.1},
	"qwen3.6-flash": {Input: 0.25, Output: 1.5, CacheRead: 0.025, CacheWrite: 0.3125},
	"qwen3.7-plus": {Input: 0.4, Output: 1.6, CacheRead: 0.04, CacheWrite: 0.5},
	"qwen3.8-max": {Input: 2, Output: 6, CacheRead: 0.17, CacheWrite: 2.5},
	"qwen3.8-max-preview": {Input: 0, Output: 0, CacheRead: 0, CacheWrite: 0},
}
